### ISSUE TITLE
Only four images are generated per epoch

### ISSUE THREAD

**Issue by pnfatnani** [Knight13/beta-VAE-disentanglement#2]
How Do I increase the number of images generated per epoch?

**Comment by Knight13** [comment]
At training time, the fit_generator uses the generator_cb callback which is a custom callback. This callback has a parameter called test_image_folder, which essentially takes in the directory of images used for testing the training, in this case, reconstructing the images. This directory can have any number of images. If you want to generate more images during your training, you'll have to increase the number of images in that directory.
